markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 温东霖的博客
desc: 小试一下

custom:
    category:
        zongjie: 项目总结
        tansuo: 探索天地
	ganxiang: 感想

    categories:
      - name:  zongjie
        title: 项目总结

      - name:  tansuo
        title: 探索天地

      - name: ganxiang
	title: 感想


    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: 温东霖
        email: 308769907@qq.com
        disqus: wsswdl.disqus.com                   # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: wsswdl                              # GitHub账号
        gravatar: 7c314334abd04d7ca3ac2c483ead0722  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
