markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 温东霖的博客
desc: 欢迎来到东霖的技术天地

custom:
    category:
        zongjie: 项目总结
        tansuo: 探索天地
        ganxiang: 感想
        sheji: 设计模式
        juc: JUC包代码

    categories:
      - name:  zongjie
        title: 项目总结

      - name:  tansuo
        title: 探索天地

      - name: ganxiang
        title: 感想

      - name: sheji
        title: 设计模式

      - name: juc
        title: JUC包代码


    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: 温东霖
        email: 308769907@qq.com
        disqus: wsswdl.disqus.com                   # Disqus缩略标识
        gcse: 010515384149699179799:j7uzkiigcai     # Google自定义搜索标识ID
        github: wsswdl                              # GitHub账号
        gravatar: 7c314334abd04d7ca3ac2c483ead0722  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://wsswdl.github.com
 